const quotes = [
    "Älä koskaan aliarvioi pienen ryhmän omistautuneiden ihmisten voimaa muuttaa maailmaa.",
    "Elämä on kuin pyöräily. Tasapainon säilyttämiseksi sinun on jatkettava liikkumista.",
    "Onni ei ole jotain valmis. Se tulee omista teoistasi.",
    "Vain ne, jotka yrittävät absurdeja asioita, voivat saavuttaa mahdottoman.",
    "Parhaat ajatukset tulevat hiljaisuudessa.",
    "Ystävyys on yksi sielu kahdessa ruumiissa.",
    "Rakastaa ja tulla rakastetuksi on tuntea aurinko molemmin puolin.",
    "Onni koostuu pienistä asioista.",
    "Elämä on liian lyhyt tuhlattavaksi vihaan.",
    "Menestys on matka, ei määränpää.",
    "Totuus on harvoin puhdas ja koskaan yksinkertainen.",
    "Elämä on taideteos, elä se kauniisti.",
    "Jokainen päivä on uusi mahdollisuus.",
    "Se, joka uskoo itseensä, voi saavuttaa kaiken.",
    "Vaikeudet tekevät meistä vahvempia.",
    "Mikään ei ole mahdotonta, jos todella haluat sen.",
    "Älä pelkää epäonnistumista, pelkää yrittämättömyyttä.",
    "Uskalla unelmoida ja uskalla elää unelmasi.",
    "Ainoa tapa tehdä suurta työtä on rakastaa sitä, mitä teet.",
    "Elämä on se, mitä tapahtuu, kun olet kiireinen tekemään muita suunnitelmia.",
    "Ole muutos, jonka haluat nähdä maailmassa.",
    "Pienet teot, suuret vaikutukset.",
    "Aloita missä olet, käytä mitä sinulla on, tee mitä voit.",
    "Kauneus on katsojan silmissä.",
    "Mitä enemmän annat, sitä enemmän saat.",
    "Elämä on oppimista, jokainen päivä on uusi oppitunti.",
    "Usko itseesi ja olet jo puolivälissä.",
    "Rakasta itseäsi ja kaikki muu loksahtaa paikoilleen.",
    "Älä seuraa polkua, tee oma polkusi ja jätä jälki.",
    "Elämä on liian lyhyt, joten elä se täysillä.",
    "Olet vahvempi kuin luulet.",
    "Positiivinen asenne tuo positiivisia tuloksia.",
    "Hymyile, se on avain moniin sydämiin.",
    "Älä koskaan luovu unelmistasi.",
    "Elämässä tärkeintä ei ole odottaa myrskyn menevän ohi, vaan oppia tanssimaan sateessa.",
    "Kaikki, mitä tarvitset, on jo sisälläsi.",
    "Tee joka päivä jotain, mitä pelkäät.",
    "Elämä on lahja, avaa se täysillä.",
    "Kaikki on mahdollista niille, jotka uskovat.",
    "Ole oma itsesi, kaikki muut ovat jo varattuja.",
    "Ole rohkea, ole vahva, ole sinä.",
    "Jokainen päivä on uusi alku.",
    "Älä anna eilisen viedä liikaa tänään.",
    "Usko ihmeisiin, koska ne tapahtuvat.",
    "Pienillä teoilla on suuri merkitys.",
    "Ole kiitollinen, elämä on kaunista.",
    "Opi eilisestä, elä tänään, toivo huomisesta.",
    "Älä odota tilaisuuksia, luo ne.",
    "Hymyile ja maailma hymyilee kanssasi.",
    "Elämä on kaunis, nauti siitä.",
    "Ole valo pimeydessä.",
    "Elä jokainen päivä kuin se olisi viimeinen.",
    "Pysy positiivisena, paremmat päivät ovat tulossa.",
    "Älä koskaan anna periksi, suuret asiat vievät aikaa.",
    "Jokainen vaikeus on mahdollisuus kasvaa.",
    "Se, joka ei yritä, ei koskaan saavuta mitään.",
    "Ole muutos, jonka haluat nähdä maailmassa.",
    "Unelmoi suuria, tee suurempia.",
    "Elämä on liian lyhyt olemaan mitään muuta kuin onnellinen.",
    "Tee joka päivä jotain, mitä rakastat.",
    "Älä anna pelon estää sinua.",
    "Onni ei ole määränpää, vaan tapa matkustaa.",
    "Ole kiitollinen siitä, mitä sinulla on, ja saat enemmän.",
    "Aloita pienestä, unelmoi suuresta.",
    "Elämä on täynnä mahdollisuuksia, tartu niihin.",
    "Ole ystävällinen, se ei maksa mitään.",
    "Elämä on matka, nauti kyydistä.",
    "Ole rohkea, ota riskejä, älä kadu mitään.",
    "Älä koskaan lopeta oppimista.",
    "Uskalla olla erilainen.",
    "Elä elämäsi ilman katumusta.",
    "Ole kiitollinen jokaisesta päivästä.",
    "Mitä ikinä teetkin, tee se sydämellä.",
    "Uskalla unelmoida, uskalla elää.",
    "Tee parasta, mitä voit, siellä missä olet, sillä mitä sinulla on.",
    "Elämä on täynnä yllätyksiä, ole valmis kaikkeen.",
    "Älä koskaan anna periksi, unelmat toteutuvat.",
    "Ole kärsivällinen, kaikki hyvä tulee aikanaan.",
    "Positiivisuus on avain onneen.",
    "Ole kiitollinen pienistä asioista.",
    "Elämä on lahja, arvosta sitä.",
    "Ole rohkea, ole vahva, älä koskaan luovuta.",
    "Usko itseesi, olet mahtava.",
    "Elämä on liian lyhyt murehtia.",
    "Pysy vahvana, paremmat päivät ovat tulossa.",
    "Ole ystävällinen, se tekee maailmasta paremman paikan.",
    "Tee tänään jotain, mitä tuleva minäsi kiittää sinua.",
    "Usko unelmiisi, ne ovat tärkeitä.",
    "Elämä on seikkailu, lähde matkalle.",
    "Ole onnellinen, se on tärkeintä.",
    "Uskalla olla erilainen, uskalla olla sinä.",
    "Jokainen päivä on uusi mahdollisuus, käytä se viisaasti.",
    "Älä koskaan lakkaa unelmoimasta.",
    "Ole sinä, kaikki muut ovat jo varattuja.",
    "Elämä on liian lyhyt tuhlattavaksi huoleen.",
    "Ole ystävällinen, maailma tarvitsee enemmän ystävällisyyttä.",
    "Elämä on matka, nauti joka hetkestä.",
    "Usko itseesi, olet ainutlaatuinen.",
    "Pysy positiivisena, hyvät asiat tapahtuvat niille, jotka uskovat."
];

function newQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    document.getElementById('quote').innerText = quotes[randomIndex];
}

document.getElementById('new-quote').addEventListener('click', newQuote);

// Näytä aloituslainaus ladattaessa sivu
newQuote();
